name: ci-cd

on:
  push:
    branches:
      - main
  workflow_dispatch:    

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20.10.0]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies 
        run: npm install                          

      - name: Update version
        uses: reedyuk/npm-version@1.1.1
        with:
          version: 1.0.${GITHUB_RUN_NUMBER}            
  
      - name: Generate
        run: npm run generate:github

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUBTOKEN }}
          publish_dir: ./dist
